name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        cache: npm
    - run: npm ci
      working-directory: ./dndsimulator
    - run: npm run build --if-present
      env: 
        CI: ""
      working-directory: ./dndsimulator
        
    - name: Install dependencies
      run: pip3 install -r requirements.txt
